# GoFrame CLI 工具配置文件
# 用于代码生成、数据库操作等开发工具的配置

# GF CLI 工具配置
gfcli:

  # 数据库配置
  gen:
    dao:
    - link: "mysql:jz:baijinyan!001@tcp(rm-cn-smw4l1pxp0001f8o.rwlb.rds.aliyuncs.com:3306)/bai_jin_yan"
      tables: ""
      removePrefix: ""
      descriptionTag: true
      noModelComment: false
      path: "./internal"
      group: "default"
      jsonCase: "CamelLower"
